---
title: "All plots for each building"
author: "Yujie Xu"
date: "1/25/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r costOverTime, fig.height=3.5}
library("dplyr")
library("readr")
namelookup = readr::read_csv("../data/gsalink_name_in_rulefile.csv") %>%
  tibble::as_data_frame() %>%
  {.}
df_zoom = readr::read_csv("../data/energy_zoom.csv")
df_area = readr::read_csv("../data/gsalink_building_area.csv")
dfrule = readr::read_csv("../data-raw/all_building_rule_2018.csv") %>%
  dplyr::group_by(building, Date) %>%
  # to make all na ones to not be connected
  dplyr::summarise(
    Cost = ifelse(sum(is.na(Cost)) < n(),
                  sum(Cost, na.rm = TRUE), sum(Cost)),
    eCost = ifelse(sum(is.na(eCost)) < n(),
                   sum(eCost, na.rm = TRUE), sum(eCost)),
    mCost = ifelse(sum(is.na(mCost)) < n(),
                   sum(mCost, na.rm = TRUE), sum(mCost)),
    sCost = ifelse(sum(is.na(sCost)) < n(),
                   sum(sCost, na.rm = TRUE), sum(sCost)),
    dur = ifelse(sum(is.na(dur)) < n(),
                 sum(dur, na.rm = TRUE), sum(dur))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(df_area) %>%
  dplyr::mutate(
    `eCost/hour` = eCost / `dur`,
    `mCost/hour` = mCost / `dur`,
    `sCost/hour` = sCost / `dur`
  ) %>%
  {.}
# buildings = readr::read_csv("../data/has_energy_ecost.csv") %>%
#   .$building
buildings = "IL0205ZZ"
for (b in buildings) {
  name = paste0(namelookup[namelookup$building==b,]$name, " ")
  p1 <- dfrule %>%
    dplyr::filter(building==b) %>%
    tidyr::gather(type, cost, Cost:sCost) %>%
    ggplot2::ggplot(ggplot2::aes(x=Date, y=cost, color=type)) +
    ggplot2::geom_line() +
    ggplot2::ggtitle(sprintf("cost composition by date: %s", b)) +
    ggplot2::xlim(c(as.Date("2018-01-01"), as.Date("2018-12-31"))) +
    ggplot2::theme(legend.position = "bottom",
                   text = ggplot2::element_text(size=10))
  print(p1)
  p2 <- dfrule %>%
    dplyr::filter(building==b) %>%
    tidyr::gather(type, `cost/hour`, `eCost/hour`:`sCost/hour`) %>%
    ggplot2::ggplot(ggplot2::aes(x=Date, y=`cost/hour`, color=type)) +
    ggplot2::geom_line() +
    ggplot2::ggtitle(sprintf("cost/hour composition by date: %s", b)) +
    ggplot2::xlim(c(as.Date("2018-01-01"), as.Date("2018-12-31"))) +
    ggplot2::theme(legend.position = "bottom",
                   text = ggplot2::element_text(size=10))
  print(p2)
  area = df_area[df_area$building==b,"GSF"][[1]]
  for (energytype in c("kWh Del Int", "Natural Gas Vol Int", "Domestic H2O Int gal")) {
    zoom_upper = df_zoom[df_zoom$building==b,energytype][[1]]
    filename = sprintf("../data-raw/building_energy/%s_%s.csv", b, energytype)
    if (file.exists(filename)) {
      energy = readr::read_csv(filename) %>%
        tibble::as.tibble()
      energy$Timestamp = as.POSIXct(energy$Timestamp,
                                    format="%m/%d/%Y %I:%M:%S %p", tz="EST")
      energy <- energy %>%
        dplyr::filter(Timestamp > as.POSIXct("2018-01-01", tz="EST"),
                      Timestamp < as.POSIXct("2018-12-31", tz="EST"))
      p <- energy %>%
        ggplot2::ggplot() +
        ggplot2::geom_line(ggplot2::aes(x=Timestamp,
                                        y=!!rlang::sym(energytype))) +
        ggplot2::ggtitle(sprintf("Building %s %s", b, energytype))
      if (!is.na(zoom_upper)) {
        p <- p +
          ggplot2::coord_cartesian(ylim=c(0, zoom_upper))
      }
      print(p)
      p <- energy %>%
        dplyr::mutate(!!rlang::sym(sprintf("%s/GSF", energytype)):=!!rlang::sym(energytype) / area) %>%
        ggplot2::ggplot() +
        ggplot2::geom_line(ggplot2::aes(x=Timestamp,
                                        y=!!rlang::sym(sprintf("%s/GSF", energytype)))) +
        ggplot2::ggtitle(sprintf("Building %s %s/GSF", b, energytype))
      if (!is.na(zoom_upper)) {
        p <- p +
          ggplot2::coord_cartesian(ylim=c(0, zoom_upper / area))
      }
      print(p)
    }
  }
  p3 <- readr::read_csv(sprintf("../data-raw/ruleStartEndByBuilding/%s_2018.csv", b),
    col_types=readr::cols(
      durationSecond = readr::col_double()
  )) %>%
  tibble::as.tibble() %>%
  dplyr::mutate(month=as.integer(format(Date, "%m"))) %>%
  dplyr::group_by(month) %>%
  dplyr::summarise(hour=sum(durationSecond)/3600, freq=n()) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(month=factor(month, levels=1:12)) %>%
  ggplot2::ggplot() +
  ggplot2::geom_bar(ggplot2::aes(x=month, y=freq), stat="identity", width=0.3) +
  ggplot2::geom_line(ggplot2::aes(x=month, y=hour, group=1)) +
  ggplot2::geom_point(ggplot2::aes(x=month, y=hour)) +
  ggplot2::ylab("frequency (bar), hour (line)") +
  ggplot2::ggtitle(sprintf("Duration and freqency of all sparks: %s", b)) +
  # ggplot2::scale_x_continuous(breaks=1:12, labels=as.character(1:12),
  #                             limits=c(0, 13)) +
  ggplot2::scale_x_discrete(drop=FALSE) +
  ggplot2::theme()
  print(p3)
}
```