---
title: "spark event start stop"
author: "Yujie Xu"
date: "1/27/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r plot, fig.height=7}
library("dplyr")
library("readr")
devtools::load_all("~/Dropbox/gsa_2017/summarise.and.plot")
namelookup = readr::read_csv("../data/gsalink_name_in_rulefile.csv") %>%
  tibble::as_data_frame() %>%
  {.}
buildings = readr::read_csv("../data/has_energy_ecost.csv") %>%
  .$building
for (b in buildings) {
  name = paste0(namelookup[namelookup$building==b,]$name, " ")
  df = readr::read_csv(sprintf("../data-raw/ruleStartEndByBuilding/%s_2018.csv", b))
  df <- df %>%
    dplyr::mutate_at(vars(Cost, eCost, mCost, sCost), function(x) as.numeric(gsub("$", "", x, fixed=TRUE))) %>%
    {.}
  df <- df %>%
    dplyr::mutate(equipRef=substr(equipRef, 32, nchar(equipRef))) %>%
    dplyr::mutate(equipRef=gsub(name, "", equipRef)) %>%
    dplyr::mutate(`eCost/hour`=eCost/(durationSecond/3600)) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(`component.group`=(strsplit(equipRef, "[_ -]"))[[1]][1]) %>%
    dplyr::ungroup() %>%
    {.}
  time.min = min(df$startPosix)
  time.max = max(df$endPosix)
  # summarise.and.plot::plot_event_start_end(
  #   df = df,
  #   event = "rule",
  #   start = "startPosix",
  #   end = "endPosix",
  #   value = "eCost/hour",
  #   time.min = time.min,
  #   time.max = time.max,
  #   title = sprintf("2018 %s spark start end", b),
  #   legend.ncol = 2,
  #   legend.fontsize = 9,
  #   legend.wrap = 30
  # )
  summarise.and.plot::scan_agg(
    df = df,
    start = "startPosix",
    end = "endPosix",
    group = "rule",
    value = "eCost/hour",
    time.min = time.min,
    time.max = time.max,
    title = sprintf("2018 %s spark eCost aggregated by rule", b),
    legend.ncol = 2,
    legend.fontsize = 9,
    legend.wrap = 30
  )
}
```
