---
title: "Jan 25 meeting prepare"
author: "Yujie Xu"
date: "1/25/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

<!-- # Tasks -->

<!-- - Check the regions of the sparks building, see if all regions are present in the study set -->
<!-- - Think about what data regions could provide -->
<!-- - Summary of the composition of e, m, s cost for each building -->

<!-- ## regions of the study set -->

<!-- Starting from a total of 68 buildings with both energy and estimated energy cost -->

```{r region}
library("readr")
library("dplyr")
# readr::read_csv("../data/gsalink_region.csv") %>%
#   dplyr::group_by(region) %>%
#   dplyr::summarise(n()) %>%
#   dplyr::ungroup() %>%
#   knitr::kable()
```

<!-- # Top 10 rules by -->

<!-- ## mCost -->

<!-- ```{r topmCost} -->
<!-- df_area = readr::read_csv("../data/gsalink_building_area.csv") -->
<!-- sumByRule = readr::read_csv("../data/spark_rule_summary_2018.csv") %>% -->
<!--   na.omit() %>% -->
<!--   dplyr::left_join(df_area) %>% -->
<!--   dplyr::group_by(rule) %>% -->
<!--   dplyr::summarise_if(is.numeric, sum) %>% -->
<!--   dplyr::ungroup() %>% -->
<!--   dplyr::select(-`count`) %>% -->
<!--   {.} -->
<!-- sumByRule %>% -->
<!--   dplyr::arrange(desc(mCost)) %>% -->
<!--   dplyr::select(rule, mCost) %>% -->
<!--   # head(n=10) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- # Buildings with top mCost under top-mCost-rules -->
<!-- ```{r topBuildingmCost, results='asis'} -->
<!-- top10 <- sumByRule %>% -->
<!--   dplyr::arrange(desc(mCost)) %>% -->
<!--   dplyr::select(rule, mCost) %>% -->
<!--   head(n=10) %>% -->
<!--   .$rule -->
<!-- for (r in top10) { -->
<!--   readr::read_csv("../data/spark_rule_summary_2018.csv") %>% -->
<!--     na.omit() %>% -->
<!--     dplyr::filter(rule==r) %>% -->
<!--     dplyr::arrange(desc(mCost)) %>% -->
<!--     dplyr::select(rule, building, mCost) %>% -->
<!--     head(n=10) %>% -->
<!--     knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) %>% -->
<!--     print() -->
<!--   print("\n") -->
<!-- } -->
<!-- ``` -->

<!-- ## eCost -->

<!-- ```{r topeCost} -->
<!-- sumByRule %>% -->
<!--   dplyr::arrange(desc(eCost)) %>% -->
<!--   dplyr::select(rule, eCost) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- ## sCost -->

<!-- ```{r topsCost} -->
<!-- sumByRule %>% -->
<!--   dplyr::arrange(desc(sCost)) %>% -->
<!--   dplyr::select(rule, sCost) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- ## Cost -->

<!-- ```{r topCost} -->
<!-- sumByRule %>% -->
<!--   dplyr::arrange(desc(Cost)) %>% -->
<!--   dplyr::select(rule, Cost) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- ## Cost/sqft -->

<!-- ```{r topCostPerGSF} -->
<!-- sumByRule %>% -->
<!--   dplyr::mutate(`Cost/GSF`=Cost / GSF) %>% -->
<!--   dplyr::arrange(desc(`Cost/GSF`)) %>% -->
<!--   dplyr::select(rule, `Cost/GSF`) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- # Cost composition -->

<!-- The following table displays the building level total estimated cost impact and duration of sparks in 2018. "Sensor Out Of Range", "Sensor Failure", "Missing Data", and "Bad Energy Data" have no cost breakdowns (NA in eCost, sCost, and mCost), so they are left out of the analysis. -->

<!-- ```{r costByBuilding} -->
<!-- df_area = readr::read_csv("../data/gsalink_building_area.csv") -->
<!-- sumByBuilding = readr::read_csv("../data/spark_rule_summary_2018.csv") %>% -->
<!--   na.omit() %>% -->
<!--   dplyr::group_by(building) %>% -->
<!--   dplyr::summarise_if(is.numeric, sum) %>% -->
<!--   dplyr::ungroup() %>% -->
<!--   dplyr::left_join(df_area) %>% -->
<!--   dplyr::select(-`count`) %>% -->
<!--   {.} -->
<!-- sumByBuilding %>% -->
<!--   dplyr::arrange(desc(Cost)) %>% -->
<!--   knitr::kable(format.args=list(big.mark=",", digits=1, scientific=F)) -->
<!-- ``` -->

<!-- The following plot shows the distribution of the three cost component. -->

<!-- ```{r costCompositionRatio, fig.width=3, fig.height=2, fig.align='center'} -->
<!-- library(ggplot2) -->
<!-- library(tidyr) -->
<!-- sumByBuilding %>% -->
<!--   dplyr::mutate(`eCost Ratio`=`eCost`/`Cost`, -->
<!--                 `mCost Ratio`=`mCost`/`Cost`, -->
<!--                 `sCost Ratio`=`sCost`/`Cost`) %>% -->
<!--   dplyr::select(building, ends_with("Ratio")) %>% -->
<!--   tidyr::gather(`cost type`, `ratio`, `eCost Ratio`:`sCost Ratio`) %>% -->
<!--   dplyr::arrange(building, `cost type`) %>% -->
<!--   ggplot2::ggplot(aes(x=`cost type`, y=ratio)) + -->
<!--   ggplot2::geom_boxplot() -->
<!-- ``` -->

## Plot individual building's cost, spark, and energy over days

This section contains building level plot of
* daily all-type spark e,s,mCost
* daily all-type spark e,s,mCost per hour
* monthly total all-type spark duration (line), and frequency (bar)
* total electricity
* total electricity/sqft

```{r costOverTime, fig.height=3}
df_area = readr::read_csv("../data/gsalink_building_area.csv")
dfrule = readr::read_csv("../data-raw/all_building_rule_2018.csv") %>%
  dplyr::group_by(building, Date) %>%
  dplyr::summarise(eCost=ifelse(sum(is.na(eCost)) < n(), 
                                sum(eCost, na.rm=TRUE), sum(eCost)),
                   mCost=ifelse(sum(is.na(mCost)) < n(), 
                                sum(mCost, na.rm=TRUE), sum(mCost)),
                   sCost=ifelse(sum(is.na(sCost)) < n(), 
                                sum(sCost, na.rm=TRUE), sum(sCost)),
                   dur=ifelse(sum(is.na(dur)) < n(), 
                                sum(dur, na.rm=TRUE), sum(dur))
                   ) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(df_area) %>%
  dplyr::mutate(`eCost/hour`=eCost / `dur`,
                `mCost/hour`=mCost / `dur`,
                `sCost/hour`=sCost / `dur`) %>%
  {.}
buildings = readr::read_csv("../data/has_energy_ecost.csv") %>%
  .$building
for (b in buildings) {
  p1 <- dfrule %>%
    dplyr::filter(building==b) %>%
    tidyr::gather(type, cost, eCost:sCost) %>%
    ggplot2::ggplot(ggplot2::aes(x=Date, y=cost, color=type)) +
    ggplot2::geom_line() +
    ggplot2::ggtitle(sprintf("cost composition by date: %s", b)) +
    ggplot2::xlim(c(as.Date("2018-01-01"), as.Date("2018-12-31"))) +
    ggplot2::theme(legend.position = "bottom",
                   text = ggplot2::element_text(size=10))
  print(p1)
  p2 <- dfrule %>%
    dplyr::filter(building==b) %>%
    tidyr::gather(type, `cost/hour`, `eCost/hour`:`sCost/hour`) %>%
    ggplot2::ggplot(ggplot2::aes(x=Date, y=`cost/hour`, color=type)) +
    ggplot2::geom_line() +
    ggplot2::ggtitle(sprintf("cost/hour composition by date: %s", b)) +
    ggplot2::xlim(c(as.Date("2018-01-01"), as.Date("2018-12-31"))) +
    ggplot2::theme(legend.position = "bottom",
                   text = ggplot2::element_text(size=10))
  print(p2)
  p3 <- readr::read_csv(sprintf("../data-raw/ruleStartEndByBuilding/%s_2018.csv", b),
      col_types=readr::cols(
        durationSecond = readr::col_double()
    )) %>%
    tibble::as.tibble() %>%
    dplyr::mutate(month=as.integer(format(Date, "%m"))) %>%
    dplyr::group_by(month) %>%
    dplyr::summarise(hour=sum(durationSecond)/3600, freq=n()) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(month=factor(month, levels=1:12)) %>%
    ggplot2::ggplot() +
    ggplot2::geom_bar(ggplot2::aes(x=month, y=freq), stat="identity", width=0.3) +
    ggplot2::geom_line(ggplot2::aes(x=month, y=hour, group=1)) +
    ggplot2::geom_point(ggplot2::aes(x=month, y=hour)) +
    ggplot2::ylab("frequency (bar), hour (line)") +
    ggplot2::ggtitle(sprintf("Duration and freqency of all sparks: %s", b)) +
    # ggplot2::scale_x_continuous(breaks=1:12, labels=as.character(1:12),
    #                             limits=c(0, 13)) +
    ggplot2::scale_x_discrete(drop=FALSE) +
    ggplot2::theme()
  print(p3)
  area = df_area[df_area$building==b,"GSF"][[1]]
  for (energytype in c("kWh Del Int", "Natural Gas Vol Int", "Domestic H2O Int gal")) {
    filename = sprintf("../data-raw/building_energy/%s_%s.csv", b, energytype)
    if (file.exists(filename)) {
      energy = readr::read_csv(filename) %>%
        tibble::as.tibble()
      energy$Timestamp = as.POSIXct(energy$Timestamp,
                                    format="%m/%d/%Y %I:%M:%S %p", tz="EST")
      energy <- energy %>%
        dplyr::filter(Timestamp > as.POSIXct("1/1/2018 12:00:00 AM", format="%m/%d/%Y %I:%M:%S %p", tz="EST"),
                      Timestamp < as.POSIXct("1/1/2019 12:00:00 AM", format="%m/%d/%Y %I:%M:%S %p", tz="EST"))
      p <- energy %>%
        ggplot2::ggplot() +
        ggplot2::geom_line(ggplot2::aes(x=Timestamp,
                                        y=!!rlang::sym(energytype))) +
        ggplot2::ggtitle(sprintf("Building %s %s", b, energytype))
      print(p)
      p <- energy %>%
        dplyr::mutate(!!rlang::sym(sprintf("%s/GSF", energytype)):=!!rlang::sym(energytype) / area) %>%
        ggplot2::ggplot() +
        ggplot2::geom_line(ggplot2::aes(x=Timestamp,
                                        y=!!rlang::sym(sprintf("%s/GSF", energytype)))) +
        ggplot2::ggtitle(sprintf("Building %s %s/GSF", b, energytype))
      print(p)
    }
  }
}
```

<!-- ## energy and spark on/off for 10 top buildings with “unoccupied cooling setpoint out of range” by energy cost -->

<!-- The buildings with highest energy cost estimate for "Unoccupied Cooling Setpoint Out of Range" are: -->

<!-- ```{r energyRule} -->
<!-- ruleToAnalyze = "Unoccupied Cooling Setpoint Out of Range" -->
<!-- toplot = readr::read_csv("../data/spark_rule_summary_2018.csv") %>% -->
<!--   dplyr::filter(rule == ruleToAnalyze) %>% -->
<!--   dplyr::arrange(desc(eCost)) %>% -->
<!--   head(n=10) %>% -->
<!--   .$building -->
<!-- toplot -->
<!-- ``` -->

<!-- Following plots individual building's rule and energy. -->

<!-- ```{r energyRulePlot, fig.height=8} -->
<!-- library(gridExtra) -->
<!-- namelookup = readr::read_csv("../data/gsalink_name_in_rulefile.csv") %>% -->
<!--   tibble::as_data_frame() %>% -->
<!--   {.} -->
<!-- r = "Unoccupied Cooling Setpoint Out of Range" -->
<!-- energytype = "kWh Del Int" -->
<!-- for (b in toplot) { -->
<!--   filename = sprintf("../data-raw/building_energy/%s_%s.csv", b, energytype) -->
<!--   if (file.exists(filename)) { -->
<!--     ## for each builidng, plot rule group by equipment, filter by type -->
<!--     name = paste0(namelookup[namelookup$building==b,]$name, " ") -->
<!--     df = readr::read_csv(sprintf("../data-raw/ruleStartEndByBuilding/%s_2018.csv", b)) -->
<!--     df <- df %>% -->
<!--       na.omit() %>% -->
<!--       dplyr::mutate_at(vars(Cost, eCost, mCost, sCost),  -->
<!--                        function(x) as.numeric(gsub("$", "", x, fixed=TRUE))) %>% -->
<!--       dplyr::filter(rule==r) %>% -->
<!--       dplyr::mutate(equipRef=substr(equipRef, 32, nchar(equipRef))) %>% -->
<!--       dplyr::mutate(equipRef=gsub(name, "", equipRef)) %>% -->
<!--       {.} -->
<!--     mindate = min(df$startPosix) -->
<!--     maxdate = max(df$endPosix) -->
<!--     energy = readr::read_csv(filename) %>% -->
<!--       na.omit() %>% -->
<!--       tibble::as_data_frame() %>% -->
<!--       dplyr::mutate_if(is.integer, as.double) %>% -->
<!--       {.} -->
<!--     energy$Timestamp = as.POSIXct(energy$Timestamp, -->
<!--                                   format="%m/%d/%Y %I:%M:%S %p", tz="EST") -->
<!--     energy <- energy %>% -->
<!--       dplyr::filter(Timestamp <= maxdate, Timestamp >= mindate) -->
<!--     p1 = df %>% -->
<!--       ggplot2::ggplot() + -->
<!--       ggplot2::geom_segment(ggplot2::aes(x=startPosix, xend=endPosix, y=eCost, yend=eCost, -->
<!--                                 group=equipRef, color=equipRef), size=2) + -->
<!--       ggplot2::ggtitle(label=sprintf("Building: %s", b), -->
<!--                        subtitle = sprintf("Rule: %s", r)) + -->
<!--       ggplot2::xlim(c(mindate, maxdate)) + -->
<!--       ggplot2::theme_bw() + -->
<!--       ggplot2::theme(legend.position = "bottom") -->
<!--     p2 = energy %>% -->
<!--       ggplot2::ggplot() + -->
<!--       ggplot2::geom_line(ggplot2::aes(x=Timestamp, y=!!rlang::sym(energytype))) -->
<!--     gridExtra::grid.arrange(p1, p2, nrow=2) -->
<!--   } -->
<!-- } -->
<!-- ``` -->