---
title: "Feb 8 meeting prepare"
author: "CMU"
date: "1/25/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

# Tasks

## Plot maintenance cost for GSALink vs non-GSALink buildings

```{r plotMaintenance}
library("readxl")
library("dplyr")
library("ggplot2")

devtools::load_all("~/Dropbox/gsa_2017/db.interface")

## contains all unique buildings
dfarea = readr::read_csv("area_info_allbuilding.csv") %>%
  dplyr::mutate(`Building Code`=substr(building, 1, 6)) %>%
  dplyr::group_by(`Building Code`) %>%
  dplyr::filter(n() == 1) %>%
  dplyr::ungroup() %>%
  dplyr::select(-`source`, -`source_order`) %>%
  {.}

allgsalink =
  readxl::read_excel("list_of_gsalink_buildings.xlsx", sheet=2) %>%
  dplyr::mutate(`building`=substr(`spark_entry`, 1 ,8)) %>%
  distinct(building) %>%
  dplyr::mutate(shortname=substr(building, 1, 6)) %>%
  {.}

studyset = readr::read_csv("../data/has_energy_ecost.csv") %>%
  dplyr::mutate(shortname=substr(building, 1, 6)) %>%
  dplyr::select(building, shortname) %>%
  {.}

alleuas = db.interface::read_table_from_db(dbname = "all", tablename = "EUAS_monthly", cols="Building_Number") %>%
  {.}

alleuas <- alleuas %>%
  dplyr::rename(building=`Building_Number`) %>%
  dplyr::distinct(building) %>%
  dplyr::mutate(shortname=substr(building, 1, 6)) %>%
  {.}

head(alleuas)

head(studyset$shortname)

df <- readxl::read_excel("maintenance_cost_from_walter/Historic O&M for Owned Buildings FY2008 - FY2017.xlsx",
                         skip=2,
                         sheet=1,
                         col_types = c("guess", "guess", "text", "text", "text",
                                       "text", "text", "text", "text", "text",
                                       "text", "text")) %>%
  {.}

head(df)

# fixme: add a for loop here
## cost.type = "A40 Mechanic Oper-Maint"
## cost.type = "A40 Mechanic Oper-Maint"
cost.type = "A30 Utilities/Fuel"

toplot <- df %>%
  tidyr::fill(`Building Code`) %>%
  dplyr::filter(`Net Income Label`==cost.type) %>%
  dplyr::mutate_at(vars(starts_with("20")), funs(as.numeric)) %>%
  dplyr::mutate(group=ifelse(`Building Code` %in% allgsalink$shortname, "GSALink",
                             ifelse(`Building Code` %in% alleuas$shortname, "EUAS non GSALink", "Other"))) %>%
  dplyr::filter(group != "Other") %>%
  dplyr::left_join(dfarea, by="Building Code") %>%
  dplyr::filter(!is.na(GSF)) %>%
  tidyr::gather(`Fiscal Year`, !!rlang::sym(cost.type), `2008`:`2017`) %>%
  dplyr::mutate_at(vars(cost.type), funs(`per GSF`=./GSF)) %>%
  dplyr::rename_at(vars("per GSF"), funs(paste(cost.type, .))) %>%
  {.}

df1 = toplot %>%
  dplyr::filter(GSF!=0) %>%
  dplyr::filter(group=="EUAS non GSALink") %>%
  {.}

df2 = toplot %>%
  dplyr::filter(GSF!=0) %>%
  dplyr::filter(group=="GSALink") %>%
  {.}

p <- ggplot2::ggplot() +
  ggplot2::geom_line(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(cost.type),
      group = `Building Code`,
      colour = group
    ),
    data = df1
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(cost.type),
      group = `Building Code`,
      colour = group
    ),
    data = df1
  ) +
  ggplot2::geom_line(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(cost.type),
      group = `Building Code`,
      colour = group
    ),
    data = df2
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(cost.type),
      group = `Building Code`,
      colour = group
    ),
    data = df2
  ) +
  ggplot2::ggtitle(sprintf("Historic O&M for All Buildings: %s", cost.type),
                   subtitle = "GSALink vs non GSALink") +
  ggplot2::ylab(paste0(cost.type, "($)"))
print(p)
ggplot2::ggsave(filename=sprintf("../plots/OandM_%s.png", gsub("/", "-", fixed = TRUE, cost.type)))

p <- ggplot2::ggplot() +
  ggplot2::geom_line(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(paste(cost.type, "per GSF")),
      group = `Building Code`,
      colour = group
    ),
    data = df1
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(paste(cost.type, "per GSF")),
      group = `Building Code`,
      colour = group
    ),
    data = df1
  ) +
  ggplot2::geom_line(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(paste(cost.type, "per GSF")),
      group = `Building Code`,
      colour = group
    ),
    data = df2
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      x = `Fiscal Year`,
      y = !!rlang::sym(paste(cost.type, "per GSF")),
      group = `Building Code`,
      colour = group
    ),
    data = df2
  ) +
  ggplot2::ggtitle(sprintf("Historic O&M for All Buildings: %s per GSF", cost.type),
                   subtitle = "GSALink vs non GSALink") +
  ggplot2::ylab(paste0(cost.type, "($/sqft)"))
print(p)
  ggplot2::ggsave(filename=sprintf("../plots/OandM_%s_perGSF.png", gsub("/", "-", fixed = TRUE, cost.type)))
```